package com.monada.storage.audit;

public enum StorageIntegrityCategory {
    MANIFEST_INVALID,
    SEGMENT_MISSING,
    ATOM_LOG_CORRUPT,
    VECTOR_SEGMENT_SIZE_MISMATCH,
    VECTOR_INDEX_MALFORMED,
    VECTOR_OFFSET_OUT_OF_BOUNDS,
    VECTOR_OFFSET_MISALIGNED,
    DUPLICATE_VECTOR_INDEX_ID,
    DUPLICATE_VECTOR_OFFSET,
    ATOM_WITHOUT_VECTOR,
    VECTOR_WITHOUT_ATOM,
    FORMAT_INCOMPATIBLE,
    FEEDBACK_LOG_CORRUPT
}
